[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
# Quitamos la actualización de pip. Solo instalamos los requerimientos.
cmds = [
    "npm install", 
    "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "npm start"